AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 100

Naming/FileName:
  Exclude: [lib/meta-rails.rb]

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
