language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0

before_install: gem install bundler

env:
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.0
  - RAILS_VERSION=4.1
  - RAILS_VERSION=4.2

sudo: false
