name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails: ['6.0', '6.1']
        ruby: ['2.6', '2.7', '3.0']
    name: Rails ${{ matrix.rails }} on Ruby ${{ matrix.ruby }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        run: bundle exec rake
